import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";
import { Providers } from "./providers/Providers";
import { edLavonia } from "./fonts";

export const metadata: Metadata = {
  title: "Restaurant Nadi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={edLavonia.variable}>
      <body
        className="font-sans antialiased leading-relaxed"
        style={{ fontFamily: "var(--font-ed-lavonia)" }}
      >
        <Providers>
          <Header />
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
