import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";

import { edLavonia } from "./fonts";
import PageLoader from "@/components/PageLoader";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Restaurant Nadi",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${edLavonia.variable}`}>
      <body className="font-sans antialiased ">
        <Providers>
          <PageLoader />
          <Header />
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
